### PR TITLE
initial webapp

### PR DESCRIPTION
**Pull request by makepanic**
Here's a first version of the webapp (without any form of style).
It's written with Ember (using https://github.com/stefanpenner/ember-app-kit to scaffold a structure with building, testing and validating). 

I took most of the code from Globe and it looks like this right now:

**index:**
- the user can choose to get graphs from all fingerprints
- the user can choose to get graphs from a selected amount of fingerprints
  2014-04-07-202502_3600x1080_scrot

**detail:**
- `/graphs/F2044413DAC2E02E3D6BCF4735A19BCA1DE97281+9695DFC35FFEB861329B9F1AB04C46397020CE31`
  2014-04-07-202514_3600x1080_scrot

Some open questions:
- where does the app gets participant fingerprints? Will there be an api?
- can the user change/insert fingerprints by himself?
- can it happen that the fingerprint request length is longer than the maximum url request length?

### CODE REVIEW

**Comment by kloesing** [comment]
Looks great!  I didn't merge it yet, because I don't know how to try it out locally.  I ran `python server-json-provider.py`.  Which file should I be looking at?

A few comments:
- Enabling users to look at subsets of fingerprints is probably overkill.  It's sufficient to just show the graphs for all fingerprints in the set.
- Regarding your question where fingerprints will come from: would it be possible to write them to a local file on the web server, or deploying them together with the web app?  I'm also thinking we shouldn't support more than a single set of fingerprints.
- This also answers your second question: no, the user shouldn't be able to change the set of fingerprints.
- Finally, regarding maximum URL request length: maybe we don't have to include fingerprints in the URL if we put fingerprints into a text file on the server.

Note that I'm trying to keep things as simple as possible.  If anything above actually makes it harder to build this web app, please let me know!

Thanks!

**Comment by makepanic** [comment]
> Looks great! I didn't merge it yet, because I don't know how to try it out locally. I ran python server-json-provider.py. Which file should I be looking at?

See https://github.com/makepanic/challenger/blob/webapp/web/README.md .
I created the python script because I needed a way to access the generated json files. 
The webapp is in the `web/dist` directory. It works like globe and can be deployed on any web server that can serve static files.

> Regarding your question where fingerprints will come from: would it be possible to write them to a local file on the web server, or deploying them together with the web app? I'm also thinking we shouldn't support more than a single set of fingerprints.

Ok. We can load the fingerprints from the challenger api server or store them in the webapp.

> This also answers your second question: no, the user shouldn't be able to change the set of fingerprints.
> Finally, regarding maximum URL request length: maybe we don't have to include fingerprints in the URL if we put fingerprints into a text file on the server.

If we store fingerprints on the server, can we create an api that returns them (something like `participants.json` with an array of objects containing the fingerprint and nickname)? The app could load them initially and use them further on.
Alternatively we could store all fingerprints in a file and use them for the server and build them into the webapp. This way we don't need to request them every time.

What do you think about displaying a list of all participants? We could print the fingerprint and nickname and link it to Atlas, Globe, ... .

**Comment by makepanic** [comment]
I removed the index page where the user can select fingerprints.
I added participants via configuration file (see https://github.com/makepanic/challenger/blob/webapp/web/config/environment.js ).

In addition i started played around with a UI we could later use:
2014-04-08-221802_3600x1080_scrot

I would like to use the full browser width and set some points where it should use a 1 column layout (i.e. max-width < 1000px).
What do you think?

**Comment by makepanic** [comment]
I fixed the tabs and added a list of all participants with links to atlas, globe, blutmagie.
I added some media queries to make it better on smaller screens:

**large resolution**
2014-04-09-213108_3600x1080_scrot
**normal resolution**
2014-04-09-213207_3600x1080_scrot
**small resolution (mobile)**
2014-04-09-213227_3600x1080_scrot

**Comment by kloesing** [comment]
Hi Christian,

I finally got the web app working here!  (It didn't long because it was hard, but because Onionoo kept me busy for too long.)

I just merged your webapp branch into my master.  I did it using command-line Git, so apparently I messed up GitHub's pull request thing...

Some feedback:
- Can we integrate the api server part into the app server part somehow?  The goal would be that we don't have two web servers running, but just one.  If you think this is possible, can you move around things in the repository, so that the web app can serve the combined-*.json files (and possibly a file with the fingerprints, see below)?
- I don't feel strongly about providing a `participants.json` or including fingerprints in the web app.  I can easily extend `challenge.py` to produce such a file from `fingerprints.txt`.  (We shouldn't serve `fingerprints.txt` directly, because it's supposed to contain comments by whoever adds fingerprints there.)
- Adding links to Globe sounds like a fine idea.  Feel free to remove links to Atlas and Blutmagie though.  Atlas doesn't support bridges, and Blutmagie is even more unmaintained.

Finally, would you mind making your repository the canonical challenger repository?  I'm happy to contribute to it, in particular to `challenger.py`.  But your contribution is more important here, and I shouldn't block you for days.  What do you think?

Thanks!

All the best,
Karsten

**Comment by makepanic** [comment]
> Some feedback:
> 
> Can we integrate the api server part into the app server part somehow? The goal would be that we don't have two web servers running, but just one. If you think this is possible, can you move around things in the repository, so that the web app can serve the combined-*.json files (and possibly a file with the fingerprints, see below)?

What server software should power challenger? If we're using something like apache we could store the generated json files in the asset directory (like http://rndm.de/challenger/vuln1648/ does with http://rndm.de/challenger/vuln1648/assets/vuln1648/ ).

> I don't feel strongly about providing a participants.json or including fingerprints in the web app. I can easily extend challenge.py to produce such a file from fingerprints.txt. (We shouldn't serve fingerprints.txt directly, because it's supposed to contain comments by whoever adds fingerprints there.)

A generated json file with all fingerprints + nicknames would be great. The app could request them in the same way it loads the combined-*.json files.

> Adding links to Globe sounds like a fine idea. Feel free to remove links to Atlas and Blutmagie though. Atlas doesn't support bridges, and Blutmagie is even more unmaintained.

Ok

> Finally, would you mind making your repository the canonical challenger repository? I'm happy to contribute to it, in particular to challenger.py. But your contribution is more important here, and I shouldn't block you for days. What do you think?

Afaik you could add me to your repository as a collaborator. This gives me full access to the repository.

Is there anything missing from the challenger web app?
Do we need the **About** page or is a landing page with information about the tor challenge enough?
Can I use text from https://www.eff.org/torchallenge on the landing page?
Should the page say "EFF Tor Challenge"? 
Is there an official logo?

Stuff I want to change:
- copy 3_days periods calculation from globe
- hide participants list by default

**Comment by kloesing** [comment]
I added you as collaborator.  Feel free to merge things as you see fit.  We probably shouldn't force-update the master branch.  But any other branch should be considered temporary.

I'd say let's use Apache.  Unless there's a reason to use something else?

For the generated json file with fingerprints and nicknames, see my fingerprints branch.  If you like it, please merge it or ask me to do that.

Regarding text for the website, I have no idea what text we need.  I'd say let's deploy the web app when you made the changes you're planning to make and then ask EFF.

**Comment by makepanic** [comment]
> I added you as collaborator. Feel free to merge things as you see fit. We probably shouldn't force-update the master branch. But any other branch should be considered temporary.

Thanks

> I'd say let's use Apache. Unless there's a reason to use something else?

Apache should be more than enough.

> For the generated json file with fingerprints and nicknames, see my fingerprints branch. If you like it, please merge it or ask me to do that.

I merged your branch.

> Regarding text for the website, I have no idea what text we need. I'd say let's deploy the web app when you made the changes you're planning to make and then ask EFF.

Sounds good. I added my changes to the project and it should be ready to deploy (see `web/README.md`).

**Pull request merged**
