### PR TITLE
Added and integrated simple OnionOO scraping

### PR DESCRIPTION
**Pull request by duk3luk3**
The script will now download documents directly from OnionOO.

Requires requests library (on debian, "python-requests" package).

Cheers,
Luke

### CODE REVIEW

**Comment by kloesing** [comment]
Tweaked your commit a bit in my luk3duk3-onionoo-integration branch.  Mind if I squash those changes into your commit?  (I couldn't test these changes, because I currently lack the bandwidth to fetch the requests package.  Will test before merging.)  Thanks!

**Comment by duk3luk3** [comment]
No problem. I'll pull the branch back into mine then I guess?

**Comment by duk3luk3** [comment]
I just looked over your commit (fc3e540), no objections at all. :)

**Comment by kloesing** [comment]
Great!  Made two more tweaks after actually running tests (see my luk3duk3-onionoo-integration branch), and pushed squashed commits to my master.  Thanks!  Closing.

**Pull request closed without merging**
